name: Deploy Salesforce code to production org

on:
  push:
    branches:
      - DevelopmentThird # change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to production org
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-version: 'latest'
          auth-url: ${{ 'https://cyntexa-5fd-dev-ed.lightning.force.com' }} # replace with the name of your secret that contains the auth URL

      - name: Retrieve metadata from GitHub repository
        run: sfdx force:source:retrieve -x package.xml -u ${{ ' wayto@perfection.com' }} # replace with the name of your secret that contains the production org username

      - name: Deploy metadata to production org
        run: sfdx force:source:deploy -x package.xml -u ${{ ' wayto@perfection.com' }} # replace with the name of your secret that contains the production org username
