name: Salesforce Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Salesforce CLI
        uses: salesforcecli/setup-sfdx@v1
      - name: Authenticate with Salesforce
        run: sfdx force:auth:jwt:grant --clientid ${{ secrets.CLIENT_ID }} --jwtkeyfile server.key --username ${{ secrets.USERNAME }} --setdefaultdevhubusername -a ${{ secrets.USERNAME }} 
      - name: Deploy to Salesforce
        run: sfdx force:source:deploy --wait 10 --testlevel RunLocalTests --sourcepath force-app/main/default/classes/MyApexClass.cls-meta.xml
