name: Salesforce Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf -
          ./sfdx/install

      - name: Deploy to org
        env:
          SF_USERNAME: ${{ secrets.USERNAME }}
          SF_PASSWORD: ${{ secrets.PASSWORD }}
          SF_LOGIN_URL: ${{ secrets.LOGIN_URL }}
          SF_CONSUMER_KEY: ${{ secrets.CLIENT_ID }}
          SF_CONSUMER_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile server.key --username $SF_USERNAME --setdefaultdevhubusername -a DevHub
          sfdx force:source:convert --outputdir deploy-package --packagename deploy-package --manifest package.xml
          sfdx force:mdapi:deploy --wait 10 --deploydir deploy-package --targetusername $SF_USERNAME
          sfdx force:apex:test:run --resultformat human --wait 10 --targetusername $SF_USERNAME

      - name: Check code
        env:
          SF_USERNAME: ${{ secrets.USERNAME }}
          SF_PASSWORD: ${{ secrets.PASSWORD }}
          SF_LOGIN_URL: ${{ secrets.LOGIN_URL }}
        run: |
          sfdx force:source:status --targetusername $SF_USERNAME
