name: Salesforce Build Validation

on:
  push:
    branches:
      - main

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli

      - name: Authenticate with Salesforce Org
        run: |
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SF_CONSUMER_KEY }} --jwtkeyfile ./server.key --username ${{ secrets.SF_USERNAME }} --setdefaultdevhubusername -a HubOrg

      - name: Validate Metadata
        run: |
          sfdx force:source:validate --json --wait 10

      - name: Check Test Coverage
        run: |
          sfdx force:apex:test:run --codecoverage --resultformat json --testlevel RunLocalTests --json > test-result.json
        continue-on-error: true

      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: 'Salesforce Code Tests'
          format: 'junit'
          path: 'test-result.json'
