on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        uses: forcedotcom/sfdx-ci@v1
        with:
          version: 'latest'

      - name: Authenticate with Salesforce Org
        run: sfdx force:auth:jwt:grant --clientid ${{ secrets.CLIENT_ID }} --jwtkeyfile ${{ secrets.SERVER }} --username ${{ secrets.USERNAME }} --setdefaultdevhubusername --setalias 'NLalw'

      - name: Deploy code to Salesforce Org
        run: sfdx force:source:deploy --sourcepath force-app --json -u https://cyntexa-5fd-dev-ed.lightning.force.com
