name: Deploy to Salesforce
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Salesforce CLI
        uses: salesforcecli/setup-sfdx@v1
        with:
          version: 'latest'
      - name: Install Dependencies
        run: |
          npm install
      - name: Deploy to Salesforce Org
        run: |
          sfdx force:auth:jwt:grant --clientid '3MVG9wt4IL4O5wvKzBvv0aR2Fik7NckrjbvoOWYN8JBqhtRfqqNgM_Yw.okbJnLyfqBpILU_IOWugt2n1ez4K' --jwtkeyfile ${{ SERVER }} --username 'wayto@perfection.com'
          sfdx force:source:deploy --sourcepath force-app/main/default --wait 10
