name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate with Salesforce Org
        run: |
          echo 'wayto@perfection.com' > ./SF_PROD_USERNAME.txt
          echo 'NJ@12345' > ./SF_PROD_PASSWORD.txt
          echo 'OUdDvA8JYTWMqcHIgfrsFP5uo' > ./SF_PROD_TOKEN.txt
          sfdx force:auth:jwt:grant --clientid 3MVG9wt4IL4O5wvKzBvv0aR2FivuC6iLpNxbIWzTaDt2jpFR3DyPniH5fXZcc_wPJaYIi4VWp2pE3xYhdXMAZ --jwtkeyfile ./jwt/server.key --username $(cat ./SF_PROD_USERNAME.txt) --password $(cat ./SF_PROD_PASSWORD.txt) --setdefaultdevhubusername -r https://cyntexa-5fd-dev-ed.lightning.force.com

      - name: Deploy Metadata to Production Org
        run: sfdx force:source:deploy -u $(cat ./SF_PROD_USERNAME.txt) -w 10

      - name: Run Apex Tests in Production
        run: sfdx force:apex:test:run -u $(cat ./SF_PROD_USERNAME.txt) -w 10 -c -r human
