name: Deploy to Salesforce

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Salesforce CLI
      run: |
        curl https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-linux-x64.tar.xz | tar xJf -
        ./sfdx/install
    - name: Deploy code to Salesforce
      env:
        SFDX_AUTH_URL: 'https://cyntexa-5fd-dev-ed.lightning.force.com'
      run: |
        sfdx force:auth:sfdxurl:store -f 'https://cyntexa-5fd-dev-ed.lightning.force.com' -d -a 'wayto@perfection.com'
        sfdx force:source:deploy -p force-app/main/default
