name: Salesforce Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm install -g sfdx-cli@latest          
          
      - name: Convert source to Metadata API format
        run: |
         mkdir unpackaged
         mv force-app/main/default unpackaged
         sfdx force:source:convert -r unpackaged -d mdapi_output_dir --loglevel debug

      - name: Create package.xml
        run: |
         echo '<?xml version="1.0" encoding="UTF-8"?><Package xmlns="http://soap.sforce.com/2006/04/metadata"><version>50.0</version></Package>' > mdapi_output_dir/package.xml

      - name: Deploy to org
        env:
          SF_USERNAME: ${{ secrets.USERNAME }}
          SF_PASSWORD: ${{ secrets.PASSWORD }}
          SF_LOGIN_URL: ${{ secrets.LOGIN_URL }}
          SF_CONSUMER_KEY: ${{ secrets.CLIENT_ID }}
          SF_CONSUMER_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile server.key --username $SF_USERNAME --setdefaultdevhubusername -a DevHub
          sfdx force:org:list
          sfdx force:project:deploy -p force-app --targetusername $SF_USERNAME
          sfdx force:apex:test:run --resultformat human --wait 10 --targetusername $SF_USERNAME


      - name: Check code
        env:
          SF_USERNAME: ${{ secrets.USERNAME }}
          SF_PASSWORD: ${{ secrets.PASSWORD }}
          SF_LOGIN_URL: ${{ secrets.LOGIN_URL }}
        run: |
          sfdx force:source:status --targetusername $SF_USERNAME
