name: Salesforce Deploy and Validate

on:
  push:
    branches:
      - main

jobs:
  deploy-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Install Salesforce CLI
        run: |
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf -
          sudo ./sfdx/install
      
      - name: Authenticate with Salesforce Org
        uses: salesforce-actions/setup-sfdx@v1
        with:
          sfdx-version: 'latest'
          auth-url: ${{ 'https://cyntexa-5fd-dev-ed.lightning.force.com' }}
          
      - name: Deploy metadata
        run: |
          sfdx force:source:deploy --sourcepath force-app --json --loglevel fatal --wait 10

      - name: Validate deployment
        run: |
          sfdx force:apex:test:run --testlevel RunLocalTests --json --loglevel error
