name: Deploy Salesforce code
on:
  push:
    branches:
      - master 
jobs:
  deploy-salesforce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-sfdx-image .
      - name: Authenticate with Salesforce org
        uses: docker://my-sfdx-image
        with:
          args: sfdx force:auth:jwt:grant --clientid '3MVG9wt4IL4O5wvKzBvv0aR2Fik7NckrjbvoOWYN8JBqhtRfqqNgM_Yw.okbJnLyfqBpILU_IOWugt2n1ez4K'  --jwtkeyfile jwt/server.key --username 'wayto@perfection.com'  --setdefaultdevhubusername -a DevHub
        env:
          SFDX_AUTH_URL: 'n1VBV100Tkni7FxDy9SNJbvUM'
          SFDX_CLIENT_ID: '3MVG9wt4IL4O5wvKzBvv0aR2Fik7NckrjbvoOWYN8JBqhtRfqqNgM_Yw.okbJnLyfqBpILU_IOWugt2n1ez4K'
          SFDX_USERNAME: 'wayto@perfection.com'
      - name: Deploy to Salesforce org
        run: |
          sfdx force:source:deploy --sourcepath force-app/main/default --targetusername 'wayto@perfection.com'
