name: Deploy to Salesforce Org

on:
  push:
    branches:
      - master

env:
  SFDX_DOMAIN_RETRY: 3
  SFDX_AUTOUPDATE_DISABLE: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf -
          sudo ./sfdx/install

      - name: Authenticate to Salesforce Org
        run: |
          echo ${{ secrets.SERVER }} | base64 --decode > server.key
          sfdx force:auth:jwt:grant --clientid 3MVG9wt4IL4O5wvKzBvv0aR2Fik7NckrjbvoOWYN8JBqhtRfqqNgM_Yw.okbJnLyfqBpILU_IOWugt2n1ez4K --jwtkeyfile server.key --username wayto@perfection.com --setdefaultdevhubusername -a wayto@perfection.com

      - name: Deploy to Salesforce Org
        run: |
          sfdx force:source:deploy --sourcepath force-app/ --json --loglevel fatal --targetusername MyHubOrg
