name: Deploy to Salesforce
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Salesforce
        env:
          PRIVATE_KEY: ${{ secrets.SERVER }}
          USERNAME: 'wayto@perfection.com'
          PASSWORD: 'NJ@1234'
        run: |
          echo "$PRIVATE_KEY" > key.pem
          sfdx force:auth:jwt:grant --clientid '3MVG9wt4IL4O5wvKzBvv0aR2Fik7NckrjbvoOWYN8JBqhtRfqqNgM_Yw.okbJnLyfqBpILU_IOWugt2n1ez4K' --jwtkeyfile key.pem --username 'wayto@perfection.com' --setdefaultdevhubusername --instanceurl https://login.salesforce.com
          sfdx force:source:deploy --sourcepath force-app/main/default --json
