name: Deploy to Salesforce Org
on:
  push:
    branches: [ master ] # Replace main with your desired branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Salesforce CLI
        uses: salesforcecli/sfdx-cli-action@v1
        with:
          version: 'latest'
      - name: Authenticate with Salesforce Org
        run: |
          sfdx auth:jwt:grant --clientid ${{ secrets.CLIENT_ID }} \
          --jwtkeyfile <(echo ${{ secrets.SERVER }} | base64 -d) \
          --username ${{ secrets.USERNAME }} --setdefaultdevhubusername
      - name: Deploy to Salesforce Org
        run: |
          sfdx force:source:deploy -u ${{ secrets.USERNAME }}

