name: Apex Build Validation
on:
  push:
  pull_request:

env:
  SFDC_USERNAME: ${{ secrets.SFDC_USERNAME }}
  SFDC_PASSWORD: ${{ secrets.SFDC_PASSWORD }}
  SFDC_SECURITY_TOKEN: ${{ secrets.SFDC_SECURITY_TOKEN }}
  SFDC_CONSUMER_KEY: ${{ secrets.SFDC_CONSUMER_KEY }}
  SFDC_INSTANCE_URL: "https://login.salesforce.com"

jobs:
  build:
    name: Build and Test Apex Code
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          export PATH=$PATH:$PWD/sfdx-cli/bin

      # Step 3: Authenticate with Salesforce Org
      - name: Authenticate with Salesforce Org
        run: |
          echo $SFDC_USERNAME
          echo $SFDC_PASSWORD
          echo $SFDC_SECURITY_TOKEN
          sfdx force:auth:jwt:grant --clientid $SFDC_CONSUMER_KEY --jwtkeyfile server.key --username $SFDC_USERNAME --setdefaultdevhubusername --setdefaultusername --instanceurl $SFDC_INSTANCE_URL

      # Step 4: Build and Test Apex Code
      - name: Build and Test Apex Code
        run: |
          sfdx force:source:deploy --sourcepath force-app --json --loglevel fatal --testlevel RunLocalTests
