name: Deploy to Salesforce using JWT Auth

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Salesforce CLI
        run: |
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf -
          export PATH=./sfdx/bin:$PATH
          sfdx --version

      - name: Create JWT token
        run: |
          export PRIVATE_KEY="$(cat ${{ secrets.SERVER }})"
          export JWT=$(echo "{}" | sfdx force:jwt:grant --clientid ${{ secrets.CLIENT_ID }} --jwtkeyfile ${{ secrets.SERVER }} --username ${{ secrets.USERNAME }} --instanceurl https://login.salesforce.com --setdefaultdevhubusername --json | jq -r '.result.access_token')
          echo $JWT

      - name: Install Dependencies
        run: |
          sfdx force:source:install --wait 10 --publishwait 10 --jwtkeyfile  ${{ secrets.SERVER }} --setdefaultdevhubusername --json

      - name: Deploy Source
        run: |
          sfdx force:source:deploy -p force-app -u ${{ env.USERNAME }} -w 10 --jwtkeyfile ${{ secrets.SERVER }} --json

