
name: Deploy to Salesforce Org
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
          ./sfdx/install
      - name: Authenticate with Salesforce
        run: |
          ./sfdx/bin/sfdx force:auth:jwt:grant --clientid '3MVG9wt4IL4O5wvKzBvv0aR2Fik7NckrjbvoOWYN8JBqhtRfqqNgM_Yw.okbJnLyfqBpILU_IOWugt2n1ez4K' --jwtkeyfile /full/path/to/server.key  --username 'wayto@perfection.com' --instanceurl https://cyntexa-5fd-dev-ed.lightning.force.com

      - name: Deploy code to Salesforce
        run: |
          ./sfdx/bin/sfdx force:source:deploy --sourcepath force-app --json --loglevel fatal
