name: Deploy to Salesforce Org
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
      SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
      SFDX_JWT_KEY: ${{ secrets.SFDX_JWT_KEY }}
      SFDX_USERNAME: ${{ secrets.SFDX_USERNAME }}
      SFDX_INSTANCE_URL: ${{ secrets.SFDX_INSTANCE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
          ./sfdx/install
      - name: Authenticate with Salesforce
        run: |
          echo "${SFDX_JWT_KEY}" | base64 --decode > server.key
          ./sfdx/bin/sfdx force:auth:jwt:grant --clientid "${SFDX_CLIENT_ID}" --jwtkeyfile server.key --username "${SFDX_USERNAME}" --instanceurl "${SFDX_INSTANCE_URL}" --setdefaultdevhubusername -a DevHub
      - name: Deploy code to Salesforce
        run: |
          ./sfdx/bin/sfdx force:source:deploy --sourcepath force-app --json --loglevel fatal
